### PR TITLE
Set cookie attribute SameSite

### PR DESCRIPTION
**Pull request by reinhardt**
Refs https://github.com/plone/plone.session/issues/29

### CODE REVIEW

**Comment by reinhardt** [comment]
@jenkins-plone-org please run jobs

**Comment by reinhardt** [comment]
@jenkins-plone-org please run jobs

**Comment by reinhardt** [comment]
Jenkins seems unstable, is that a known issue? On the first run the 3.9 job was green, the others had differing failures. On the second run all is red.

**Comment by reinhardt** [comment]
@jenkins-plone-org please run jobs

**Review by mauritsvanrees — APPROVED** [review]
LGTM.
Jenkins should be more stable now, let's try again:

@jenkins-plone-org please run jobs

**Review by jensens — APPROVED** [review]

**Comment by Rudd-O** [comment]
We also need an easy way to set up the cookie lifetime.  Currently the cookie expires based on the session machinery's setting but that setting is extremely obscure and can only be found through the ZMI.

**Comment by jensens** [comment]
@Rudd-O I agree, but having a Control panel is out of scope of this PR.

**Comment by reinhardt** [comment]
Jenkins still has failures that seem unrelated. Is there anything we can do except re-run them?

@jenkins-plone-org please run jobs

**Comment by reinhardt** [comment]
Ooh, jenkins is green now!

**Comment by ale-rt** [comment]
See also https://github.com/zopefoundation/Products.Sessions/pull/48/

**Pull request merged**
