### PR TITLE
fix dependency indirection to CMFPlone

### PR DESCRIPTION
**Pull request by jensens**
Do not hold hard dependencies to ``Products.CMFPlone``.

### CODE REVIEW

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by gforcada** [comment]
Rather than making copies of functions right and left to avoid dependency loops, why not find a better place for these kind of utils? `plone.api` ? Somewhere else? my 0,2 cents :)

**Comment by jensens** [comment]
Unless we have such a package its better to copy. At least ``plone.api`` is not the package you want it to be, it is the other way around: it depends on almost all other packages. Also, when we skip Python 3 in Plone 6 we can avoid these complex functions almost.

**Comment by agitator** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Pull request merged**
